### ISSUE TITLE
PasswordToken hint method should return Option<&str> and not Option<&String>

### ISSUE THREAD

**Issue by jonnyfer** [Lonami/grammers#131]
As the title says, is there a specific reason why the `hint` method of `grammers_client::types::password_token::PasswordToken` returns an `Option<&String>`?

I was trying to write something like:
`println!("hint: {}", password_token.hint().unwrap_or_else(|| "None"));`
but this of course doesn't work, because a `&String` is required.

Now, it should be pretty easy to make `hint` return an `Option<&str>` instead, with:
`self.password.hint.as_ref().and_then(|s| Some(&s[..]))`

What do you think about it?

**Comment by AndrielFR** [comment]
```rust
pub fn hint(&self) -> Option<&str> {
  self.password.hint.as_deref()
}
```

is enough to fix it.

**Comment by Lonami** [comment]
> is there a specific reason why the `hint` method of `grammers_client::types::password_token::PasswordToken` returns an `Option<&String>`?

Technically, there is no reason to "take power away" by using a type which allows the user to do less things (`str` is "less" "powerful" than `String`). So `String` was used, because there was no reason for grammers to use the more-restricted type.

But I agree it's generally more annoying to use so I'm fine with the proposed change.

**Comment by jonnyfer** [comment]
Thank you
