### ISSUE TITLE
message.chat().username() always None

### ISSUE THREAD

**Issue by AIPACMan** [Lonami/grammers#212]
Is this the correct behavior when a user writes for the first time, then `message.chat().username()` == Some('Username'). But when the same user writes subsequent messages, message.chat().username() is always None

**Comment by Lonami** [comment]
Sounds about right. Telegram doesn't include all sender information because it assumes you already have it. Only way to solve it would be to either add a cache to grammers (not happening, that has a lot of other problems to solve) or always make a request (wasteful, some users won't need it).

Therefore, there's nothing to do here. Code should rely on the ID, not the username.
